FROM node:latest

# Create app directory
WORKDIR /be

# Install app dependencies
COPY package*.json ./
RUN npm install

npm i -g concurrently

# Copy app source code
COPY . .

#Expose port and start application
EXPOSE 8080
CMD [ "npm", "startC" ]