version: "2"

services:
    service:
        container_name: server
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - mongo
        links:
            - mongo
        environment:
            PORT: 3000
            NODE_ENV: production
            MONGODB_URI: mongodb://root:IN0KfPvwvTADta1tLNrML5fWmXYosfDk@mongo:27017/db?authSource=admin
            SALT: radnomstring
            KEY_GENERATION_PASSPHRASE: asdadasfkhbdsakfebk
            JWT_SECRET_KEY: SomeSecretKeyTest
            JWT_EXPIRATION_TIME: 300
            PATH_TO_PDF_FILE: ..\src\assets\sample.pdf

    mongo:
        image: mongo:latest
        container_name: mongo
        environment:
            - MONGO_INITDB_DATABASE=db
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=IN0KfPvwvTADta1tLNrML5fWmXYosfDk
        volumes:
            - /mongo-db-backup:/data/db
