version: "2"
services:
  app:
    container_name: task_manager
    restart: always
    build: .
    ports:
      - "8000:3000"
    links:
      - mongo
    environment:
        MONGO: 27017
        DNS_ADDRESS: "https://task-manager-arturziemba.herokuapp.com/"
        PORT: 3000
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - "27017:27017"